allowBuilds:
  '@clerk/shared': set this to true or false
  browser-tabs-lock: set this to true or false
  bufferutil: set this to true or false
  core-js: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
