import { useMemo, useState } from 'react';
import { Alert, Platform, ScrollView, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { acceptBooking, advanceBooking, createBooking, Booking, Driver } from '@/lib/designated-driver';
import { useDesignatedDriver } from '@/store/designated-driver';

type Role = '乘客' | '司機' | '管理';
const ink = '#122d26', green = '#14745b', pale = '#eef6f1', line = '#dce7e0';
const today = new Date(); const expiryDefault = `${today.getFullYear() + 1}-${String(today.getMonth()+1).padStart(2,'0')}-${String(today.getDate()).padStart(2,'0')}`;
const msg = (s: string) => Platform.OS === 'web' ? globalThis.alert?.(s) : Alert.alert('安心代駕', s);
const Btn = ({title,onPress,quiet=false}: {title:string;onPress:()=>void;quiet?:boolean}) => <TouchableOpacity onPress={onPress} style={{backgroundColor:quiet?'white':green,borderColor:quiet?line:green,borderWidth:1,paddingVertical:13,paddingHorizontal:16,borderRadius:13,marginTop:9,alignItems:'center'}}><Text style={{color:quiet?ink:'white',fontSize:15,fontWeight:'700'}}>{title}</Text></TouchableOpacity>;
const Field = ({label,value,onChange,placeholder='',keyboard='default'}: {label:string;value:string;onChange:(s:string)=>void;placeholder?:string;keyboard?:'default'|'numeric'}) => <View style={{marginTop:12}}><Text style={{color:'#50635b',fontSize:13,fontWeight:'600',marginBottom:6}}>{label}</Text><TextInput value={value} onChangeText={onChange} placeholder={placeholder} keyboardType={keyboard} autoCapitalize={keyboard==='default'?'characters':'none'} style={{borderWidth:1,borderColor:line,borderRadius:12,paddingHorizontal:13,paddingVertical:12,fontSize:16,color:ink,backgroundColor:'white'}} /></View>;
export default function AnxinDemo() {
 const {data,update}=useDesignatedDriver(); const [role,setRole]=useState<Role>('乘客'); const [pickup,setPickup]=useState('中環德輔道中 88 號'); const [destination,setDestination]=useState('九龍尖沙咀廣東道 100 號'); const [plate,setPlate]=useState('AB1234'); const [vehicle,setVehicle]=useState('Toyota Corolla'); const [transmission,setTransmission]=useState<'自動波'|'手動波'>('自動波'); const [condition,setCondition]=useState('右後門有舊刮痕，車燈正常'); const [insuranceReference,setInsuranceReference]=useState('DEMO-POLICY-001'); const [insuranceExpiry,setInsuranceExpiry]=useState(expiryDefault); const [insuranceConfirmed,setInsuranceConfirmed]=useState(false); const [authorization,setAuthorization]=useState(false);
 const [selected,setSelected]=useState<string|null>(null); const [driverName,setDriverName]=useState('測試司機 陳先生');
 const selectedBooking=data.bookings.find(b=>b.id===selected); const active=useMemo(()=>data.bookings.filter(b=>!['completed','cancelled'].includes(b.status)),[data.bookings]);
 const patch=(fn:(s:typeof data)=>typeof data)=>update(fn(data));
 const submit=()=>{try{const booking=createBooking({pickup,destination,plate,vehicle,transmission,condition,insuranceReference,insuranceExpiry,insuranceConfirmed,authorization});patch(s=>({...s,bookings:[booking,...s.bookings]}));setSelected(booking.id);setRole('司機');msg('測試訂單已建立。切換管理角色批准司機，再切到司機上線及接單。');}catch(e){msg(e instanceof Error?e.message:'資料無效');}};
 const act=(next:Booking['status'])=>{if(!selectedBooking)return;try{const b=advanceBooking(selectedBooking,next);patch(s=>({...s,bookings:s.bookings.map(x=>x.id===b.id?b:x)}));}catch(e){msg(e instanceof Error?e.message:'操作未能完成');}};
 const toggleCheck=(key:'plateChecked'|'conditionChecked'|'insuranceChecked'|'keysReturned'|'customerConfirmed')=>{if(!selectedBooking)return;const b={...selectedBooking,[key]:!selectedBooking[key]};patch(s=>({...s,bookings:s.bookings.map(x=>x.id===b.id?b:x)}));};
 const currentDriver=data.drivers.find(x=>x.id==='demo-driver')!;
 const setDriver=(fn:(d:Driver)=>Driver)=>patch(s=>({...s,drivers:s.drivers.map(d=>d.id==='demo-driver'?fn(d):d)}));
 const card={backgroundColor:'white',borderColor:line,borderWidth:1,borderRadius:18,padding:16,marginTop:14};
 const title={fontSize:20,fontWeight:'800' as const,color:ink};
 const row=(label:string,value:string)=><View style={{flexDirection:'row',justifyContent:'space-between',paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#edf1ee'}}><Text style={{color:'#5a6c64'}}>{label}</Text><Text style={{color:ink,fontWeight:'700',maxWidth:'58%',textAlign:'right'}}>{value}</Text></View>;
 const step=(label:string,checked:boolean,key:Parameters<typeof toggleCheck>[0])=><TouchableOpacity key={key} onPress={()=>toggleCheck(key)} style={{flexDirection:'row',alignItems:'center',paddingVertical:10}}><View style={{width:23,height:23,borderRadius:7,borderWidth:1,borderColor:checked?green:'#aebcb4',backgroundColor:checked?green:'white',alignItems:'center',justifyContent:'center',marginRight:10}}><Text style={{color:'white',fontWeight:'800'}}>{checked?'✓':''}</Text></View><Text style={{fontSize:15,color:ink}}>{label}</Text></TouchableOpacity>;
 return <SafeAreaView style={{flex:1,backgroundColor:'#f5f8f5'}}><ScrollView contentContainerStyle={{padding:18,paddingBottom:38,maxWidth:650,width:'100%',alignSelf:'center'}}>
   <View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><View><Text style={{color:green,fontWeight:'800',letterSpacing:1}}>ANXIN · 安心代駕</Text><Text style={{fontSize:26,fontWeight:'800',color:ink,marginTop:5}}>自己架車，安心返屋企</Text></View><View style={{backgroundColor:pale,borderRadius:99,paddingHorizontal:12,paddingVertical:8}}><Text style={{color:green,fontWeight:'700'}}>免費測試版</Text></View></View>
   <Text style={{color:'#62736b',marginTop:7,lineHeight:21}}>司機駕駛客人自己的車。以示範資料走一次乘客、司機及管理流程。</Text>
   <View style={{flexDirection:'row',backgroundColor:'#e9efea',padding:4,borderRadius:14,marginTop:18}}>{(['乘客','司機','管理'] as Role[]).map(r=><TouchableOpacity key={r} onPress={()=>setRole(r)} style={{flex:1,padding:10,borderRadius:11,alignItems:'center',backgroundColor:role===r?'white':'transparent'}}><Text style={{fontWeight:'700',color:role===r?green:'#66756e'}}>{r}</Text></TouchableOpacity>)}</View>
   {role==='乘客'&&<>
    <View style={card}><Text style={title}>預約代駕</Text><Text style={{color:'#687970',marginTop:5}}>落單後由合資格司機駕駛你的車送你到目的地。</Text><Field label="接車地點" value={pickup} onChange={setPickup}/><Field label="目的地" value={destination} onChange={setDestination}/><Field label="車牌" value={plate} onChange={setPlate} placeholder="例如 AB1234"/><Field label="車款" value={vehicle} onChange={setVehicle}/><View style={{flexDirection:'row',gap:8,marginTop:11}}>{(['自動波','手動波'] as const).map(t=><TouchableOpacity key={t} onPress={()=>setTransmission(t)} style={{flex:1,padding:12,borderRadius:12,borderWidth:1,borderColor:transmission===t?green:line,backgroundColor:transmission===t?pale:'white',alignItems:'center'}}><Text style={{color:transmission===t?green:ink,fontWeight:'700'}}>{t}</Text></TouchableOpacity>)}</View><Field label="車況及已有損傷" value={condition} onChange={setCondition}/><Field label="保單參考（測試資料）" value={insuranceReference} onChange={setInsuranceReference}/><Field label="保險到期日 YYYY-MM-DD" value={insuranceExpiry} onChange={setInsuranceExpiry}/>
     {[[insuranceConfirmed,setInsuranceConfirmed,'已向保險公司確認代駕服務及司機受保'],[authorization,setAuthorization,'我是車主或已獲車主授權使用車輛']] .map(([value,set,label]:any)=><View key={label} style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:11}}><Text style={{color:ink,flex:1,paddingRight:8,lineHeight:20}}>{label}</Text><Switch value={value} onValueChange={set} trackColor={{true:green}}/></View>)}
     <Btn title="建立免費測試訂單" onPress={submit}/><Text style={{fontSize:12,color:'#738078',marginTop:9,lineHeight:18}}>示範版不連線、不收款。保險資料由測試者填寫，並無連線查核保單。</Text>
    </View>
    <View style={card}><Text style={title}>我的行程 · {active.length} 張進行中</Text>{data.bookings.length===0?<Text style={{color:'#748178',marginTop:12}}>尚未有訂單。可以用上方表格建立測試行程。</Text>:data.bookings.map(b=><TouchableOpacity key={b.id} onPress={()=>setSelected(b.id)} style={{paddingVertical:12,borderBottomWidth:1,borderColor:line}}><Text style={{fontWeight:'700',color:ink}}>{b.pickup} → {b.destination}</Text><Text style={{color:green,marginTop:4}}>{b.status}　{b.plate}</Text></TouchableOpacity>)}</View>
   </>}
   {role==='管理'&&<>
    <View style={card}><Text style={title}>司機審核</Text><Text style={{color:'#687970',marginTop:5}}>測試用審核開關。正式版須接駁管理員登入及資格核實。</Text><Text style={{color:ink,fontWeight:'700',marginTop:15}}>{currentDriver.name}</Text><Text style={{color:'#687970',marginTop:4}}>駕駛資格、香港身份及保險文件需由管理員核實</Text><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:10}}><Text style={{color:ink}}>批准接單</Text><Switch value={currentDriver.approved} onValueChange={v=>setDriver(d=>({...d,approved:v}))} trackColor={{true:green}}/></View></View>
    <View style={card}><Text style={title}>訂單管理 · {data.bookings.length}</Text>{data.bookings.length===0?<Text style={{color:'#748178',marginTop:12}}>新訂單會顯示於此。</Text>:data.bookings.map(b=><TouchableOpacity key={b.id} onPress={()=>setSelected(b.id)} style={{paddingVertical:12,borderBottomWidth:1,borderColor:line}}><Text style={{fontWeight:'700',color:ink}}>{b.id} · {b.plate}</Text><Text style={{color:'#687970',marginTop:4}}>{b.pickup} → {b.destination}</Text><Text style={{color:green,marginTop:4}}>{b.status} · {b.vehicle} · 保險到期 {b.insuranceExpiry}</Text></TouchableOpacity>)}</View>
   </>}
   {role==='司機'&&<>
    <View style={card}><Text style={title}>司機接單</Text><Text style={{color:'#687970',marginTop:5}}>接單前需經管理角色批准，再切換上線。</Text><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:13}}><Text style={{color:ink}}>司機資料</Text><Text style={{color:currentDriver.approved?green:'#a35416',fontWeight:'700'}}>{currentDriver.approved?'已批准':'待管理員批准'}</Text></View><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:8}}><Text style={{color:ink}}>上線接單</Text><Switch value={currentDriver.online} onValueChange={v=>setDriver(d=>({...d,online:v}))} disabled={!currentDriver.approved} trackColor={{true:green}}/></View></View>
    <View style={card}><Text style={title}>可接訂單</Text>{data.bookings.filter(b=>b.status==='requested').length===0?<Text style={{color:'#748178',marginTop:12}}>目前沒有待接訂單。</Text>:data.bookings.filter(b=>b.status==='requested').map(b=><View key={b.id} style={{borderTopWidth:1,borderColor:line,marginTop:12,paddingTop:12}}><Text style={{fontWeight:'700',fontSize:16,color:ink}}>{b.pickup} → {b.destination}</Text><Text style={{color:'#607168',marginTop:5}}>客人車輛：{b.vehicle}　{b.transmission}</Text><Text style={{color:'#607168',marginTop:3}}>車牌：{b.plate}　保險到期：{b.insuranceExpiry}</Text><Text style={{color:'#607168',marginTop:3}}>車況：{b.condition}</Text><Btn title="接取訂單" onPress={()=>{try{const s=acceptBooking(data,b.id,'demo-driver');update(s);setSelected(b.id);}catch(e){msg(e instanceof Error?e.message:'未能接單');}}}/></View>)}</View>
   </>}
   {selectedBooking&&<View style={card}><Text style={title}>行程及現場核對</Text><Text style={{color:green,fontWeight:'700',marginTop:6}}>{selectedBooking.id} · {selectedBooking.status}</Text>{row('接車',selectedBooking.pickup)}{row('目的地',selectedBooking.destination)}{row('客人車輛',`${selectedBooking.vehicle} · ${selectedBooking.plate}`)}{row('車主授權',selectedBooking.authorization?'已確認':'未確認')}{row('保險聲明',`${selectedBooking.insuranceReference} · ${selectedBooking.insuranceExpiry}`)}
    {step('現場車牌與登記資料一致',selectedBooking.plateChecked,'plateChecked')}{step('已與客人確認車身狀況及損傷',selectedBooking.conditionChecked,'conditionChecked')}{step('已核對保單資料及代駕保障',selectedBooking.insuranceChecked,'insuranceChecked')}{step('已交還車匙',selectedBooking.keysReturned,'keysReturned')}{step('客人確認行程完成',selectedBooking.customerConfirmed,'customerConfirmed')}
    {selectedBooking.status==='accepted'&&<Btn title="到達接車地點" onPress={()=>act('arrived')}/ >}{selectedBooking.status==='arrived'&&<Btn title="核對完成，開始代駕" onPress={()=>act('driving')}/ >}{selectedBooking.status==='driving'&&<Btn title="完成行程" onPress={()=>act('completed')}/ >}
    <Text style={{fontWeight:'700',color:ink,marginTop:14}}>行程紀錄</Text>{selectedBooking.events.map((e,i)=><Text key={i} style={{color:'#687970',marginTop:5}}>{new Date(e.at).toLocaleString('zh-HK')} · {e.action}</Text>)}
   </View>}
   <View style={{marginTop:18,padding:14,backgroundColor:'#fff8e9',borderRadius:14}}><Text style={{fontWeight:'700',color:'#6f5018'}}>開發測試說明</Text><Text style={{color:'#765f33',marginTop:5,lineHeight:20}}>所有狀態只保存在目前裝置。開發版模擬核對流程，沒有真實身份／保險驗證、司機配對、即時定位、付款或管理員帳戶；勿輸入真實個人、保單或車輛資料。</Text></View>
   <TouchableOpacity onPress={()=>{patch(()=>({version:1,drivers:[{id:'demo-driver',name:'測試司機 陳先生',approved:false,online:false}],bookings:[]}));setSelected(null);}} style={{alignSelf:'center',padding:13,marginTop:8}}><Text style={{color:'#8a5347'}}>清除本機測試資料</Text></TouchableOpacity>
  </ScrollView></SafeAreaView>;
}
